### ISSUE TITLE
Voter Refactoring

### ISSUE THREAD

**Issue by adamkay97** [adamkay97/CSSD_Subtask3#3]
Removing test voter functions from main index page.
Moving admin voter methods to admin module from voter module.

**Comment by KieranPhilp** [comment]
Will look into this and update with findings.

**Comment by KieranPhilp** [comment]
Code used in Index.cshtml is now unused, so i will remove that and refactor the voter module. Which involves moving admin specific tools to the admin module rather than the votermodule
